version: '3.8'

services:
  backend:
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "127.0.0.1:5000:5000"
    expose:
      - 5000
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - MONGODB_DATABASE=recipeDB
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    expose:
      - 3000

  mongo:
    image: mongo:4.4
    restart: always
    volumes:
      - mongo-data:/data/db

volumes:
    mongo-data: